//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace piler_inc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_transactions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_transactions()
        {
            this.tbl_cart = new HashSet<tbl_cart>();
            this.tbl_payment = new HashSet<tbl_payment>();
        }
    
        public int trans_id { get; set; }
        public Nullable<System.DateTime> trans_date { get; set; }
        public Nullable<int> trans_product { get; set; }
        public Nullable<int> trans_buyer { get; set; }
        public Nullable<int> trans_quantity { get; set; }
        public Nullable<double> trans_discount { get; set; }
        public string trans_status { get; set; }
    
        public virtual tbl_accounts tbl_accounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_cart> tbl_cart { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_payment> tbl_payment { get; set; }
        public virtual tbl_products tbl_products { get; set; }
    }
}
