//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace piler_inc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ads
    {
        public int ad_id { get; set; }
        public string ad_name { get; set; }
        public string ad_StartDate { get; set; }
        public string ad_EndDate { get; set; }
        public string ad_page { get; set; }
        public string ad_image { get; set; }
    }
}
