//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace piler_inc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_payment
    {
        public int payment_id { get; set; }
        public Nullable<System.DateTime> payment_date { get; set; }
        public Nullable<int> trans_id { get; set; }
        public string payment_type { get; set; }
        public string payment_status { get; set; }
    
        public virtual tbl_transactions tbl_transactions { get; set; }
    }
}
