//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace piler_inc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_threads
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_threads()
        {
            this.tbl_inquiries = new HashSet<tbl_inquiries>();
        }
    
        public int thread_id { get; set; }
        public string thread_title { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_inquiries> tbl_inquiries { get; set; }
    }
}
