//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace piler_inc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_cart
    {
        public int cart_id { get; set; }
        public Nullable<int> trans_id { get; set; }
        public Nullable<int> product_id { get; set; }
        public Nullable<int> cart_quantity { get; set; }
    
        public virtual tbl_products tbl_products { get; set; }
        public virtual tbl_transactions tbl_transactions { get; set; }
    }
}
