//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace piler_inc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_products()
        {
            this.tbl_cart = new HashSet<tbl_cart>();
            this.tbl_transactions = new HashSet<tbl_transactions>();
        }
    
        public int product_id { get; set; }
        public string product_name { get; set; }
        public string product_desc { get; set; }
        public Nullable<double> product_price { get; set; }
        public Nullable<int> product_owner { get; set; }
        public Nullable<int> product_quantity { get; set; }
        public string prod_img { get; set; }
    
        public virtual tbl_accounts tbl_accounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_cart> tbl_cart { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_transactions> tbl_transactions { get; set; }
    }
}
