//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace piler_inc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_inquiries
    {
        public int inq_id { get; set; }
        public string inq_content { get; set; }
        public Nullable<System.DateTime> inq_date { get; set; }
        public Nullable<int> inq_from { get; set; }
        public Nullable<int> inq_to { get; set; }
        public Nullable<int> thread_id { get; set; }
    
        public virtual tbl_accounts tbl_accounts { get; set; }
        public virtual tbl_accounts tbl_accounts1 { get; set; }
        public virtual tbl_threads tbl_threads { get; set; }
    }
}
